const { cmd } = require('../command');
const axios = require('axios');
const fs = require('fs');
const path = require('path');

cmd({
    pattern: "numbers1",
    alias: ["numtxt1", "numbers01"],
    desc: "Search numbers and send as TXT file",
    category: "search",
    react: "📑",
    filename: __filename
}, async (conn, mek, m, { from, q, reply }) => {
    try {
        if (!q) return reply("❌ Please provide a country code or search term.\nExample: .numbers 92");

        await conn.sendMessage(from, { react: { text: "⏳", key: mek.key } });

        // API Call
        const apiUrl = `https://drkamran-api-site.vercel.app/api/search/pinterest?q=${encodeURIComponent(q)}`;
        const response = await axios.get(apiUrl);
        const data = response.data;

        if (!data || !data.status || !data.result || data.result.length === 0) {
            await conn.sendMessage(from, { react: { text: "❌", key: mek.key } });
            return reply(`❌ No data found for "${q}".`);
        }

        // 1. TXT File Content Tyar Karein
        let txtContent = `NUMBERS LIST FOR: ${q}\n\n`;
        data.result.forEach((item, index) => {
            txtContent += `${index + 1}. Name: ${item.name || 'N/A'} | Number: ${item.number || 'N/A'}\n`;
        });

        // 2. File ko Temporary Save Karein
        const fileName = `Numbers_${q}.txt`;
        const filePath = path.join(__dirname, fileName);
        fs.writeFileSync(filePath, txtContent);

        // 3. Stylish Caption Tyar Karein (Screenshot ki tarah)
        const caption = `📊 *NUMBERS DATABASE*
━━━━━━━━━━━━━━━━━━━━━
🌐 *CODE:* +${q}
📈 *TOTAL:* ${data.result.length} ACTIVE
━━━━━━━━━━━━━━━━━━━━━
🔗 *CHANNEL:* https://whatsapp.com/channel/0029Vb8ZRggFHWq8vcVyQ13p

> *GENERATED BY KAMRAN-MD*`;

        // 4. TXT File Send Karein
        await conn.sendMessage(from, {
            document: fs.readFileSync(filePath),
            mimetype: 'text/plain',
            fileName: fileName,
            caption: caption
        }, { quoted: mek });

        // 5. Cleanup: File delete karein
        fs.unlinkSync(filePath);
        await conn.sendMessage(from, { react: { text: "✅", key: mek.key } });

    } catch (e) {
        console.error("TXT API ERROR:", e.message);
        await conn.sendMessage(from, { react: { text: "❌", key: mek.key } });
        reply("❌ Error generating file.");
    }
});
