const { cmd } = require('../command');
const axios = require('axios');
const FormData = require('form-data');
const fs = require('fs');
const path = require('path');
const os = require('os');

/**
 * Aha-Music (doreso.com) API handler
 */
async function aha_music(filePath) {
    const form = new FormData();
    form.append('file', fs.createReadStream(filePath));
    form.append('sample_size', 118784);
    
    const { data } = await axios.post(
        'https://api.doreso.com/humming', 
        form, 
        {
            headers: {
                ...form.getHeaders(),
                'user-agent': 'Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Mobile Safari/537.36',
                'accept': 'application/json, text/plain, */*',
                'origin': 'https://www.aha-music.com',
                'referer': 'https://www.aha-music.com/'
            },
            maxBodyLength: Infinity,
            maxContentLength: Infinity
        }
    );
    return data;
}

cmd({
    pattern: "findsong",
    alias: ["shazam", "whatsong"],
    react: "🎶",
    desc: "Find song title by replying to an audio/voice message.",
    category: "tools",
    filename: __filename
},           
async (conn, mek, m, { from, reply, quoted }) => {
    let tmpPath = null;
    try {
        // 1. آڈیو چیک کریں (LID Safe)
        const quotedMsg = quoted || m;
        const mime = (quotedMsg.msg || quotedMsg).mimetype || "";

        if (!/audio|video/.test(mime)) {
            return reply("⚠️ Please reply to an *audio* or *voice* message to identify the song.");
        }

        await conn.sendMessage(from, { react: { text: "⏳", key: m.key } });

        // 2. میڈیا ڈاؤن لوڈ کریں
        const buffer = await conn.downloadMediaMessage(quotedMsg);
        if (!buffer) return reply("❌ Failed to download audio.");

        // 3. عارضی فائل بنائیں
        tmpPath = path.join(os.tmpdir(), `shazam_${Date.now()}.mp3`);
        fs.writeFileSync(tmpPath, buffer);

        // 4. Shazam/Aha API کال کریں
        const result = await aha_music(tmpPath);

        // 5. رزلٹ ہینڈلنگ
        if (result && result.data && result.data.title) {
            const { title, artists } = result.data;
            const caption = `🎵 *Song Identified!*\n\n` +
                          `📌 *Title:* ${title}\n` +
                          `👤 *Artist:* ${artists}\n\n` +
                          `*Generated by Aha-Music*`;
            
            await conn.sendMessage(from, { text: caption }, { quoted: mek });
            await conn.sendMessage(from, { react: { text: "✅", key: m.key } });
        } else {
            await conn.sendMessage(from, { react: { text: "❓", key: m.key } });
            reply("❌ Could not identify this song. Make sure the audio is clear and at least 5-10 seconds long.");
        }

    } catch (err) {
        console.error("Shazam Error:", err);
        await conn.sendMessage(from, { react: { text: "❌", key: m.key } });
        reply(`❌ Error: ${err.message || "An error occurred during song identification."}`);
    } finally {
        // 6. صفائی (Cleanup)
        if (tmpPath && fs.existsSync(tmpPath)) {
            fs.unlinkSync(tmpPath);
        }
    }
});
