const { cmd } = require('../command');
const yts = require("yt-search");
const axios = require("axios");

cmd({
    pattern: "song",
    alias: ["ytmp3", "play"],
    react: "🎵",
    desc: "YouTube search & MP3 play",
    category: "download",
    use: ".play ",
    filename: __filename
},
async (arslan, mek, m, { from, args, reply }) => {
    try {
        const query = args.join(" ");
        if (!query) return reply("❌ Please Provide Me A song Query or Link");

        await arslan.sendMessage(from, { react: { text: "⏳", key: m.key } });

        /* 🔍 Faster Search */
        const search = await yts(query);
        if (!search.videos || !search.videos.length) return reply("❌ No result Found");

        const video = search.videos[0];
        
        /* 🎧 MP3 API - Optimized Timeout */
        // URL encoding added to prevent slow parsing
        const apiUrl = `https://arslan-apis.vercel.app/download/ytmp3?url=${encodeURIComponent(video.url)}`;

        // Timeout reduced to 25s for better bot responsiveness
        const res = await axios.get(apiUrl, { timeout: 25000 });

        if (!res.data?.result?.download?.url) {
             return reply("❌ Audio Not Generated by API.");
        }

        const dlUrl = res.data.result.download.url;
        const meta = res.data.result.metadata;

        /* 🎵 SEND AUDIO - Optimized Context */
        await arslan.sendMessage(from, {
            audio: { url: dlUrl },
            mimetype: "audio/mpeg",
            ptt: false,
            fileName: `${meta.title || "song"}.mp3`,
            contextInfo: {
                externalAdReply: {
                    title: (meta.title || video.title).substring(0, 40),
                    body: "KAMRAN-MD DOWNLOADER",
                    thumbnailUrl: video.thumbnail,
                    sourceUrl: video.url,
                    mediaType: 1,
                    renderLargerThumbnail: false // Setting to false makes it load faster
                }
            }
        }, { quoted: mek });

        await arslan.sendMessage(from, { react: { text: "✅", key: m.key } });

    } catch (err) {
        console.error("PLAY ERROR:", err);
        reply("❌ Server busy or Timeout. Try again.");
        await arslan.sendMessage(from, { react: { text: "❌", key: m.key } });
    }
});
                  
